# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Î»labs
email: lambda@labs.com
description: > # this means to ignore newlines until "baseurl:"
        A blog-like conversation about programming languages, communication
        and the human condition.
baseurl:
url: "http://lambda-labs.github.com" # the base hostname & protocol for your site
twitter_username: 
github_username:  lambda-labs

# Build settings
markdown: kramdown
kramdown:
  parse_block_html: true
gems:
  - jekyll-paginate
paginate: 2
